### ISSUE TITLE
Add “Run workflow” button (`workflow_dispatch`) to Pull Request Action

### ISSUE THREAD

**Issue by mdwigley** [enterlucent/nucleusaf#15]
## Detailed Description
Our current GitHub Actions run only on `push` / `pull_request` events.  
Adding a `workflow_dispatch` trigger will let maintainers kick off a build, test, or publish job from the GitHub UI or via the REST/CLI without having to force-push a dummy commit.

Concrete changes:

* Update each `pull_request` workflow YAML under `.github/workflows/` to include

```yaml
...
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    workflow_dispatch:        # <-- new
...
```

## Context
* Occasionally we need to re-run CI after updating repository secrets, self-hosted runner images, or external services.  
* Maintainers running GitHub CLI (`gh workflow run`) can trigger a pipeline from the terminal.

This quality-of-life change benefits every contributor with merge rights and keeps the history clean for everyone else.

## Related Issues
- None

## Target Platform(s)
GitHub Actions (all operating-system matrix entries remain unchanged).
